spring:
  application:
    name: Platzi market
  datasource:
    url: jdbc:postgresql://localhost:5432/platzi-market
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /platzi-market/api/
